CREATE DATABASE SENAI_HROADS_TARDE;

USE SENAI_HROADS_TARDE;

CREATE TABLE TIPO_DE_HABILIDADE(
	 ID TINYINT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE HABILIDADES(
	 ID TINYINT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
	,ID_TIPO_DE_HABILIDADE TINYINT FOREIGN KEY REFERENCES TIPO_DE_HABILIDADE(ID)
);

CREATE TABLE CLASSES(
	 ID TINYINT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE CLASSES_HABILIDADES(
	 ID_CLASSE TINYINT FOREIGN KEY REFERENCES CLASSES(ID)
	,ID_HABILIDADES TINYINT FOREIGN KEY REFERENCES HABILIDADES(ID)
);

CREATE TABLE PERSONAGENS(
	 ID TINYINT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,ID_CLASSE TINYINT FOREIGN KEY REFERENCES CLASSES(ID)
	,CAP_MAX_VIDA TINYINT NOT NULL
	,CAP_MAX_MANA TINYINT NOT NULL
	,DATA_ATT DATETIME
	,DATA_CRIACAO DATETIME NOT NULL
);