USE SENAI_HROADS_TARDE;

SELECT * FROM PERSONAGENS --6

SELECT * FROM CLASSES --7

SELECT NOME FROM CLASSES --8

SELECT ID,NOME FROM HABILIDADES --9

SELECT COUNT (*) FROM HABILIDADES --10

SELECT ID FROM HABILIDADES ORDER BY ID ASC --11 

SELECT * FROM TIPO_DE_HABILIDADE --12


SELECT HABILIDADES.NOME AS NOME_HABILIDADE, TIPO_DE_HABILIDADE.NOME AS NOME_TIPO_DE_HABILIDADE FROM --13
	HABILIDADES LEFT JOIN TIPO_DE_HABILIDADE
ON
	HABILIDADES.ID_TIPO_DE_HABILIDADE = TIPO_DE_HABILIDADE.ID


SELECT PERSONAGENS.NOME AS NOME_PERSONAGEM, CLASSES.NOME AS NOME_CLASSE FROM --14
	PERSONAGENS LEFT JOIN CLASSES
ON
	PERSONAGENS.ID_CLASSE = CLASSES.ID


SELECT PERSONAGENS.NOME AS NOME_PERSONAGEM, CLASSES.NOME AS NOME_CLASSE FROM --15
	PERSONAGENS RIGHT JOIN CLASSES
ON
	PERSONAGENS.ID_CLASSE = CLASSES.ID



SELECT CLASSES_HABILIDADES. *, CLASSES.NOME AS NOME_CLASSE, HABILIDADES.NOME AS NOME_HABILIDADE FROM --16	
	CLASSES_HABILIDADES
INNER JOIN
	CLASSES ON CLASSES_HABILIDADES.ID_CLASSE = CLASSES.ID
INNER JOIN
	HABILIDADES ON CLASSES_HABILIDADES.ID_HABILIDADES = HABILIDADES.ID



SELECT CLASSES_HABILIDADES. *, CLASSES.NOME AS NOME_CLASSE, HABILIDADES.NOME AS NOME_HABILIDADE FROM --17	
	CLASSES_HABILIDADES
RIGHT JOIN
	CLASSES ON CLASSES_HABILIDADES.ID_CLASSE = CLASSES.ID
RIGHT JOIN
	HABILIDADES ON CLASSES_HABILIDADES.ID_HABILIDADES = HABILIDADES.ID



SELECT CLASSES_HABILIDADES. *, CLASSES.NOME AS NOME_CLASSE, HABILIDADES.NOME AS NOME_HABILIDADE FROM --18	
	CLASSES_HABILIDADES
LEFT JOIN
	CLASSES ON CLASSES_HABILIDADES.ID_CLASSE = CLASSES.ID
LEFT JOIN
	HABILIDADES ON CLASSES_HABILIDADES.ID_HABILIDADES = HABILIDADES.ID

	



